# Generates red "hanko" stamp PNGs with a Japanese font and writes them,
# base64-encoded, into src/main/stamp-assets.ts. Run on Windows (needs Yu Gothic).
#   powershell -ExecutionPolicy Bypass -File scripts/gen-stamp-assets.ps1
# The PNGs are baked into source so the runtime needs no CJK font in mupdf.
# NOTE: kept pure ASCII (chars are built from code points) so Windows PowerShell
# 5.1 parses it correctly regardless of the file's encoding/BOM.

Add-Type -AssemblyName System.Drawing

$ErrorActionPreference = 'Stop'
$size  = 512
$red   = [System.Drawing.Color]::FromArgb(255, 192, 40, 45)
$inset = 26.0
$radius = 46.0

# key -> stamp definition. Keys must match StampKind in types.ts.
#   mode 'v' = vertical CJK stack (cps = Unicode code points, top to bottom)
#   mode 'h' = single horizontal line (text = ASCII string)
#   maru-hi          = U+79D8                      (hi)
#   shagaihi         = U+793E U+5916 U+79D8        (shagai-hi)
#   toriatsukai-chui = U+53D6 U+6271 U+6CE8 U+610F (toriatsukai-chui)
#   fukusei-genkin   = U+8907 U+88FD U+53B3 U+7981 (fukusei-genkin)
$stamps = [ordered]@{
  'maru-hi'          = @{ mode = 'v'; cps = @(0x79D8) }
  'shagaihi'         = @{ mode = 'v'; cps = @(0x793E, 0x5916, 0x79D8) }
  'toriatsukai-chui' = @{ mode = 'v'; cps = @(0x53D6, 0x6271, 0x6CE8, 0x610F) }
  'fukusei-genkin'   = @{ mode = 'v'; cps = @(0x8907, 0x88FD, 0x53B3, 0x7981) }
  'confidential'     = @{ mode = 'h'; text = 'CONFIDENTIAL' }
}

function New-RoundedRect([System.Drawing.RectangleF]$rect, [single]$rad) {
  $path = New-Object System.Drawing.Drawing2D.GraphicsPath
  $d = $rad * 2
  $path.AddArc($rect.X, $rect.Y, $d, $d, 180, 90)
  $path.AddArc($rect.Right - $d, $rect.Y, $d, $d, 270, 90)
  $path.AddArc($rect.Right - $d, $rect.Bottom - $d, $d, $d, 0, 90)
  $path.AddArc($rect.X, $rect.Bottom - $d, $d, $d, 90, 90)
  $path.CloseFigure()
  return $path
}

$entries = @()

foreach ($key in $stamps.Keys) {
  $def  = $stamps[$key]
  $mode = $def.mode

  $bmp = New-Object System.Drawing.Bitmap($size, $size, [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
  $g   = [System.Drawing.Graphics]::FromImage($bmp)
  $g.SmoothingMode     = [System.Drawing.Drawing2D.SmoothingMode]::AntiAlias
  $g.TextRenderingHint = [System.Drawing.Text.TextRenderingHint]::AntiAlias
  $g.Clear([System.Drawing.Color]::Transparent)

  # outer rounded frame
  $frame = New-Object System.Drawing.RectangleF($inset, $inset, ($size - 2 * $inset), ($size - 2 * $inset))
  $pen = New-Object System.Drawing.Pen($red, 22)
  $pen.LineJoin = [System.Drawing.Drawing2D.LineJoin]::Round
  $path = New-RoundedRect $frame $radius
  $g.DrawPath($pen, $path)

  $brush = New-Object System.Drawing.SolidBrush($red)
  $sf = New-Object System.Drawing.StringFormat
  $sf.Alignment     = [System.Drawing.StringAlignment]::Center
  $sf.LineAlignment = [System.Drawing.StringAlignment]::Center

  if ($mode -eq 'h') {
    # single horizontal line, font scaled to fit the inner width
    $text  = $def.text
    $innerW = $size - 2 * $inset - 60.0
    $probe = New-Object System.Drawing.Font('Arial', 100.0, [System.Drawing.FontStyle]::Bold, [System.Drawing.GraphicsUnit]::Pixel)
    $measured = $g.MeasureString($text, $probe)
    $probe.Dispose()
    $fontPx = [Math]::Min(100.0 * ($innerW / $measured.Width), $size * 0.32)
    $font = New-Object System.Drawing.Font('Arial', [single]$fontPx, [System.Drawing.FontStyle]::Bold, [System.Drawing.GraphicsUnit]::Pixel)
    $rect = New-Object System.Drawing.RectangleF(0, 0, $size, $size)
    $g.DrawString($text, $font, $brush, $rect, $sf)
    $font.Dispose()
  }
  else {
    # vertically stacked CJK characters
    $cps = $def.cps
    $n   = $cps.Length
    $innerTop    = 60.0
    $innerBottom = $size - 60.0
    $cell        = ($innerBottom - $innerTop) / $n
    $fontPx      = [Math]::Min($cell * 0.82, $size * 0.6)
    $font = New-Object System.Drawing.Font('Yu Gothic UI', [single]$fontPx, [System.Drawing.FontStyle]::Bold, [System.Drawing.GraphicsUnit]::Pixel)
    for ($i = 0; $i -lt $n; $i++) {
      $ch = [string][char][int]$cps[$i]
      $cellRect = New-Object System.Drawing.RectangleF(0, ($innerTop + $i * $cell), $size, $cell)
      $g.DrawString($ch, $font, $brush, $cellRect, $sf)
    }
    $font.Dispose()
  }

  $ms = New-Object System.IO.MemoryStream
  $bmp.Save($ms, [System.Drawing.Imaging.ImageFormat]::Png)
  $b64 = [Convert]::ToBase64String($ms.ToArray())

  $g.Dispose(); $bmp.Dispose(); $pen.Dispose(); $brush.Dispose(); $ms.Dispose()

  $entries += "  '$key':`n    '$b64'"
  Write-Host "rendered $key : $($b64.Length) b64 chars"
}

$header = @'
// AUTO-GENERATED by scripts/gen-stamp-assets.ps1 - do not edit by hand.
// Red hanko stamp images as base64 PNG, rendered with a Japanese font at build
// time. Baked into source so the runtime needs no CJK font in mupdf. To change
// the stamp set, edit the script and re-run it.

/* eslint-disable */
export const STAMP_PNG_BASE64: Record<string, string> = {
'@

$body = ($entries -join ",`n") + "`n}`n"
$content = $header + "`n" + $body

$outPath = Join-Path $PSScriptRoot '..\src\main\stamp-assets.ts'
$enc = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($outPath, $content, $enc)
Write-Host "wrote $outPath"
